[package]
name = "arrow"
version = "0.1.0"
authors = ["Jihoon Son <jihoonson@apache.org>"]
build = "build.rs"

[lib]
name = "arrow"
path = "src/lib.rs"

[dependencies]
libc = "0.2.11"

[build-dependencies]
gcc = "0.3.28"
